POST https://node-nint.onrender.com/videos
Content-Type: application/json

{
    "title": "Video a ser apagado",
    "description": "Esse video vai ser apagado",
    "duration": 150
}

###

GET https://node-nint.onrender.com/videos

###

PUT https://node-nint.onrender.com/videos/afb04171-fc9a-41cc-ba83-cabc82c90c3b
Content-Type: application/json

{
    "title": "Video apagado",
    "description": "Esse video vai ser apagado",
    "duration": 220
}

###

DELETE https://node-nint.onrender.com/videos/a79b90d6-a519-4451-b533-4aadc6501f51